#config_version=4

# search for keyword "TODO" for easy things to customize your first game.

# ---------------
# MODES
# ---------------
config:
- modes.yaml

# ---------------
# DISPLAY
# ---------------
window:
  width: 960
  height: 540
  title: My first FAST game
  resizable: true
  fullscreen: false
  borderless: true
  exit_on_escape: true

displays:
  window:
    width: 960
    height: 540
  dmd:
    width: 240
    height: 134    
    default: true

slides:
  dmd_parent:
    - type: color_dmd
      width: 960
      height: 540   
      gain: 1.0
      bg_color: 101010ff
      blur: 0.1
      pixel_size: 0.87
      dot_filter: True      
        
slide_player:
  mc_ready:
    dmd_parent:
      target: window
      
# ---------------
# CONFIG
# ---------------
game:
  balls_per_game: 1
  max_players: 1

machine:
  # Standard FAST trough is six balls
  balls_installed: 6
  min_balls: 1
  
Widget_Styles:
  text_default:
    # TODO place your font in the "fonts" folder, and re-name "DefaultFont", or change the name here.
    font_name: DefaultFont
    font_size: 10
  tall_title:
    # TODO place your font in the "fonts" folder, and re-name "DefaultFont", or change the name here.
    font_name: DefaultFont
    font_size: 10

# ---------------
# AUDIO/VIDEO
# ---------------
sound_system:
  buffer: 4096
  frequency: 44100
  channels: 2
  master_volume: 1
  tracks:
    voice:
      volume: 1
      simultaneous_sounds: 1
      preload: yes
    sfx:
      volume: 1
      simultaneous_sounds: 8
      preload: yes
    music:
      volume: 1
      simultaneous_sounds: 1

assets:
    sounds:
        default:
            load: preload
        voice:
            load: preload
            track: voice
        sfx:
            load: preload
            track: sfx
        music:
            load: preload
            track: music
    videos:
        default:
            load: preload
#            
sounds:
    # TODO rename your attract music file to "Music_1.wav" and place in the folder "sounds/music"
    # or change the name below to match your file.
    Music_1:
        target: music

videos:
    # TODO silimar to music, rename your attract video file to "Video_1.mp4" and place in the folder "videos"
    # or change the name below to match your file.
    Video_1:
        file: Video_1.mp4

# ---------------
# HARDWARE
# ---------------
fast:
  # TODO set your ports to the names you find in your own system, under the "dev" folder.
  ports: /dev/tty.usbserial-142B, /dev/tty.usbserial-142C
  config_number_format: int
  #debug: True
hardware:
  driverboards: fast
  platform: fast
  #platform: smart_virtual
  
# ---------------
# HARDWARE / SWITCHES
# ---------------
switches:

  # ---------------
  # HARDWARE / SWITCHES / TROUGH
  # ---------------
  # These switches are numbered according to the connector on the FAST trough,
  # assuming you plug into the first connection on the first driver board.
  s_trough_1:
    number: 0
    label:
    tags:
    type: NC
  s_trough_2:
    number: 1
    label:
    tags:
    type: NC
  s_trough_3:
    number: 2
    label:
    tags:
    type: NC
  s_trough_4:
    number: 3
    label:
    tags:
    type: NC
  s_trough_5:
    number: 4
    label:
    tags:
    type: NC
  s_trough_6:
    number: 5
    label:
    tags:
    type: NC
  s_trough_jam:
    number: 6
    label:
    tags:
    type: 'NO'
  s_plunger_lane:
    number: 7
    label:
    tags:

  # ---------------
  # HARDWARE / SWITCHES / CABINET
  # ---------------
  s_start:
    number: 8
    label:
    tags: start, player
  s_flipper_left:
    number: 9
    tags: player, flipper_left
    label:
  s_flipper_right:
    number: 10
    tags: player, flipper_right
    label:

  # ---------------
  # HARDWARE / SWITCHES / PLAYFIELD
  # ---------------
  s_slingshot_left:
    number: 11
    label:
    tags: playfield_active, slingshot
  s_slingshot_right:
    number: 12
    label:
    tags: playfield_active, slingshot

# ---------------
# HARDWARE / COIL
# ---------------
coils:
  
  # ---------------
  # HARDWARE / COIL / FLIPPERS
  # ---------------
  c_flipper_left_main:
    number: 0
    pulse_ms: 100
  c_flipper_left_hold:
    number: 1
    pulse_ms: 100
    hold_power: 4
    #allow_enable: true
  c_flipper_right_main:
    number: 2
    pulse_ms: 100
  c_flipper_right_hold:
    number: 3
    pulse_ms: 100
    hold_power: 3
    #allow_enable: true
    
  # ---------------
  # HARDWARE / COIL / PLAYFIELD
  # ---------------
  c_trough_eject:
    number: 4
    label:
    tags:
    pulse_ms: 25
  c_plunger_lane:
    number: 5
    label:
    tags:
    pulse_ms: 25
  c_slingshot_left:
    number: 6
    label:
    tags:
  c_slingshot_right:
    number: 7
    label:
    tags:

# ---------------
# HARDWARE / AUTOFIRE
# ---------------
flippers:
  left:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
  right:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right

autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right

# ---------------
# HARDWARE / BALL DEVICES
# ---------------
ball_devices:

  trough:
    tags: trough, home, drain
    ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5, s_trough_6, s_trough_jam
    eject_coil: c_trough_eject
    confirm_eject_type: target
    eject_targets: plunger_lane
    jam_switch: s_trough_jam

  plunger_lane:
    tags: ball_add_live
    ball_switches: s_plunger_lane
    eject_coil: c_plunger_lane
    

# ---------------
# VIRTUAL
# ---------------
keyboard:
    z:
        switch: s_flipper_left
    /:
        switch: s_flipper_right
    1:
        switch: s_trough_1
        toggle: true
    2:
        switch: s_trough_2
        toggle: true
    3:
        switch: s_trough_3
        toggle: true
    4:
        switch: s_trough_4
        toggle: true
    5:
        switch: s_trough_5
        toggle: true
    6:
        switch: s_trough_6
        toggle: true
    p:
        switch: s_plunger_lane
        toggle: true
    s:
        switch: s_start


virtual_platform_start_active_switches:
    s_trough_1
    s_trough_2
    s_trough_3
    s_trough_4
    s_trough_5
    s_trough_6