# config_version=4
# n2

mode:
  start_events: ball_starting
  priority: 8500

ball_saves:
  default:
    #active_time: 10s
    active_time: 2s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    debug: true

  #multiball:
  #  #active_time: 10s
  #  active_time: 2s
  #  hurry_up_time: 2s
  #  grace_period: 2s
  #  enable_events: enable_the_ball_save
  #  timer_start_events: enable_the_ball_save
  #  auto_launch: true
  #  balls_to_save: -1
  #  debug: true


slide_player:
  ball_save_default_saving_ball: slide_1

    
#sound_player:
#  ball_saved1: Dont_Give_Up
#  ball_saved2: im_sorry
#  ball_saved3: sorry_ill_be_good

#random_event_player:
#  ball_save_default_saving_ball:
#  - ball_saved1
#  - ball_saved2
#  - ball_saved3
  
slides:
  slide_1:
    widgets:
      # BLUE FORGROUND
      - type: text
        style: tall_title
        font_size: 32
        color: 0000ff
        text: Ball Saved
        y: middle
        x: middle
        animations: 
          entrance:
          - property: font_size
            value: 32
            duration: 2000ms
            timing: with_previous
          #- property: font_size
          #  value: 150
          #  duration: 1000ms
          #  timing: after_previous
          - property: opacity
            value: 0
            duration: 1000ms
            #timing: with_previous
            timing: after_previous
      # GREEN OUTLINE
      - type: text
        style: tall_title
        font_size: 32
        color: 00ff00
        text: Ball Saved
        y: middle-1
        x: middle-1
        animations: 
          entrance:
          - property: font_size
            value: 32
            duration: 2000ms
            timing: with_previous
          #- property: font_size
          #  value: 150
          #  duration: 1000ms
          #  timing: after_previous
          - property: opacity
            value: 0
            duration: 1000ms
            #timing: with_previous
            timing: after_previous
      - type: text
        style: tall_title
        font_size: 32
        color: 00ff00
        text: Ball Saved
        y: middle+1
        x: middle+1
        animations: 
          entrance:
          - property: font_size
            value: 32
            duration: 2000ms
            timing: with_previous
          #- property: font_size
          #  value: 150
          #  duration: 1000ms
          #  timing: after_previous
          - property: opacity
            value: 0
            duration: 1000ms
            #timing: with_previous
            timing: after_previous
      - type: text
        style: tall_title
        font_size: 32
        color: 00ff00
        text: Ball Saved
        y: middle+1
        x: middle-1
        animations: 
          entrance:
          - property: font_size
            value: 32
            duration: 2000ms
            timing: with_previous
          #- property: font_size
          #  value: 150
          #  duration: 1000ms
          #  timing: after_previous
          - property: opacity
            value: 0
            duration: 1000ms
            #timing: with_previous
            timing: after_previous
      - type: text
        style: tall_title
        font_size: 32
        color: 00ff00
        text: Ball Saved
        y: middle-1
        x: middle+1
        animations: 
          entrance:
          - property: font_size
            value: 32
            duration: 2000ms
            timing: with_previous
          #- property: font_size
          #  value: 150
          #  duration: 1000ms
          #  timing: after_previous
          - property: opacity
            value: 0
            duration: 1000ms
            #timing: with_previous
            timing: after_previous
    #expire: 1.5s 
    expire: 3.0s
    
#show_player:
  #ball_save_default_enabled:
  #  red_flash:
  #    key: ball_save_flash
  #    show_tokens:
  #      leds: rgb_keepshooting
  #    speed: 4
  #    loops: -1
  #ball_save_default_disabled:
  #  ball_save_flash:
  #    action: stop
  #ball_save_multiball_enabled:
  #  blue_flash:
  #    key: ball_save_flash
  #    show_tokens:
  #      leds: rgb_keepshooting
  #    speed: 4
  #    loops: -1
  #ball_save_multiball_disabled:
  #  ball_save_flash:
  #    action: stop


