#config_version=5

mpf:
  default_show_sync_ms: 500
  
# ---------------
# MODES
# ---------------
config:
# -----------------
- configDisplays.yaml
- configMusic.yaml
    
# ---------------
# CONFIG
# ---------------
game:
  balls_per_game: 3
  max_players: 1
  allow_start_with_loose_balls: true

machine:
  # Standard FAST trough is six balls
  balls_installed: 2
  min_balls: 1


sound_system:
  buffer: 4096
  frequency: 44100
  channels: 2
  master_volume: 1
  tracks:
    voice:
      volume: 1.0
      simultaneous_sounds: 1
      preload: yes
    sfx:
      volume: 0.8
      simultaneous_sounds: 8
      preload: yes
    music:
      volume: 0.9
      simultaneous_sounds: 8    
    trackplaylist:
      type: playlist
      volume: 0.9
      crossfade_time: 0.1s

assets:
  sounds:
    default:
      load: on_demand
    voice:
      load: on_demand
      track: voice
    sfx:
      load: on_demand
      track: sfx
    music:
      load: on_demand
      track: music
  videos:
    default:
      load: on_demand
  images:
    default:
      load: on_demand
